env: "local" #local, virtual, dev, prod
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8082"
  timeout: 4s  #Время на чтение запроса
  iddle_timeout: 60s   #Нам не нужно для каждого запроса одного клиента открывать несколько соединений, мы обрабатываем их в одном. Если запросы от клиента не приходили 60 секунд, то обрываем это соединение.
  